const express = require("express");
const dotenv = require("dotenv").config();
const cors = require('cors');
const PORT = process.env.PORT || 5000;
const {errorHandler} =  require('./middleware/errorMiddleware');
const connectToDatabase = require('./connect/database');
connectToDatabase();
const app = express();
app.use(express.json());
app.use(express.urlencoded({extended :  false}));
app.use(cors());
app.use('/api/tasks', require('./routes/taskRoutes'));
app.use('/api/users', require('./routes/userRoutes'));
app.use(errorHandler);
app.listen(PORT, ()=>console.log(`Server listening on ${PORT}`));